### ISSUE TITLE
TCK Challenge: ClaimValueInjectionTest and ProviderInjectionTest not according to spec

### ISSUE THREAD

**Issue by tomas-langer** [eclipse/microprofile-jwt-auth#117]
According to specification section 4.3:
```
Custom claims not handled by the Claims enum are required to be valid JSON-P javax.json.JsonValue subtypes.
```
Yet the tests mentioned above break this requirement. Class `ClaimValueInjectionEndpoint` contains the following section:
```java
@Inject
@Claim("custom-missing")
private ClaimValue<Optional<Long>> custom;
@Inject
@Claim("customString")
private ClaimValue<String> customString;
```

Both are breaking the specification. There is a mention that "Optional<Long>" may get an Optional.empty() if the claim is not present (regardless of its possible types). 
This is a strange note, as the "custom-missing" claim may not be missing eventually, and then it would be broken - so the validation would pass, and runtime fail, even though the spec clearly says the validation should fail.

**Comment by starksm64** [comment]
Yes, there is inconsistent handling of custom claim types when wrapped in a ClaimValue vs the raw type. ClaimValueInjectionEndpoint will need to be updated.

**Comment by sberyozkin** [comment]
My understanding is that most implementations use `String` for simple claims which are actually strings, and to be honest I'd rather relax the spec to support it as opposed to requiring the users deal with JsonString while at the same tile letting them do `String` for the spec-visible claims

**Comment by sberyozkin** [comment]
Will try to come up with some text relaxing this requirement

**Comment by radcortez** [comment]
How about if we just drop the current requirement and say something along the lines of these:

**Original Text**:
Custom claims not handled by the Claims enum are required to be valid JSON-P `javax.json.JsonValue` subtypes. The
current complete set of valid claim types is therefore, (excluding the invalid Claims.UNKNOWN Void type):

* java.lang.String
* java.lang.Long
* java.lang.Boolean
* java.util.Set<java.lang.String>
* javax.json.JsonValue.TRUE/FALSE
* javax.json.JsonString
* javax.json.JsonNumber
* javax.json.JsonArray
* javax.json.JsonObject

**Proposed Text**:
The current complete set of valid claim types are:

* java.lang.String
* java.lang.Long
* java.lang.Boolean
* java.util.Set<java.lang.String>
* javax.json.JsonValue (including all subtypes)

Custom claims not handled by the Claims enum must use any of the types defined in the previous acceptable claim types list. If a different type is used, the deployment must fail with a `DeploymentException`.  The custom claim is automatically converted to the type used in the injection point.

**Comment by sberyozkin** [comment]
Listing JSON types is more descriptive as it is a limited set, we won't save much by the optimization like `including all subtypes`.
So to have 
```
@Inject
@Claim("customString")
private ClaimValue<String> customString;
```
working, your text should be fine except that we don't really need IMHO to differentiate between standard and custom claims, having your
```
The claims are automatically converted to the type used in the injection point where the type must be any of the types defined in the previous acceptable claim types list.
```

This will cover everything. The only problem is that I don't think we can actually fix it for `1.2`, because there will be still no solution for the consistent representation of a given claim when doing `jwt.getClaim("someclaim")` - this will still may return something that may not match what is injected. At least in 2.0 we'll have an option to match with the typed conversion.

**Comment by radcortez** [comment]
Even if we cannot make the complete fix in `1.2` and have consistency between injection and programatic lookup, we should fix the injection part.

Right now, the specs just says: 

> Custom claims not handled by the Claims enum are required to be valid JSON-P `javax.json.JsonValue` subtypes.

So this is leaving any other supported type out. And since we mention that conversion only happens at injection point, I think it is fine to leave it as is, since there is no conversion happening in the programatic API.

**Comment by sberyozkin** [comment]
> Even if we cannot make the complete fix in 1.2 and have consistency between injection and programatic lookup, we should fix the injection part.

+1.

**Comment by radcortez** [comment]
Ok, so new proposed text:

The current complete set of valid claim types are:

* java.lang.String
* java.lang.Long (and primitive long)
* java.lang.Boolean (and primitive boolean)
* java.util.Set<java.lang.String>
* javax.json.JsonValue.TRUE/FALSE
* javax.json.JsonString
* javax.json.JsonNumber
* javax.json.JsonArray
* javax.json.JsonObject

The claims are automatically converted to the type used in the injection point where the type must be any of the types defined in the previous acceptable claim types list.

And I think we are safe in the programatic API, since conversion is only mentioned for the injection point. Is this ok?

**Comment by radcortez** [comment]
@sberyozkin I believe this one can also be closed with https://github.com/eclipse/microprofile-jwt-auth/pull/181
