### ISSUE TITLE
Clarification on "Recommended Headers and Claims"

### ISSUE THREAD

**Issue by ghunteranderson** [eclipse/microprofile-jwt-auth#225]
I may be a bit late to the party here 🙂. 

Reviewing the new differentiation between required and recommended claims, I was a little confused who the recommendation is directed at; MP-JWT implementers or token issuers. 

At first, I assumed it is recommended but optional for token issuers provide recommended claims. Then, to maintain interoperability, I would expect those recommended claims be optional in every implementation of MP-JWT. Regardless of the application server chosen, we would know that an IDP that provides the minimum required claims can operate with that MP-JWT implementation.

Then I ran across this line and I was a little confused.
> [NOTE] MP JWT implementations may enforce that JWT tokens contain all the recommended headers and claims. The recommended headers and claims may become required in the future versions of the MP JWT specification.

To me, this line implies that it is recommended that implementers of MP-JWT require the claim. That is, the minimum required claims are allowed to vary by implementation. I worry that this will create IDPs who claim to support MP-JWT but they only provide the claims required by some implementations and not others. If interoperability is the goal, allowing the minimum required claims to vary by implementation doesn't seem conducive.

I suppose my hope for this issue is to
1. Get clarification on what "recommended" means in this spec and 
2. Question if allowing required claims to vary by implementation is the right approach (assuming I understood that correctly)

**Comment by sberyozkin** [comment]
@ghunteranderson Hi,

> To me, this line implies that it is recommended that implementers of MP-JWT require the claim

`recommended` is about the best practice but it is not a requirement to be MP JWT compliant for a given IDP provider to include all those recommended claims - I'd say all the certified providers do include them, but since we are also deaking with the self-issued tokens we are keeping the option open for such clients to continue operating.

Every implementation should always have a freedom to differentiate when it comes down to the specific production level requirements where the security of a given application is more important than the compliance.

If we set in stone that all N recommended claims must always be there then we end up excluding the real world token flows where a given required claim makes no much sense.

We should continue moving slowly and making more recommended claims as required - but we need some practical evidence we don't limit the reach of MP JWT by doing it

**Comment by ghunteranderson** [comment]
Hey @sberyozkin,

Thanks for taking time to respond 🙂. This clears up the intent some for me.

> Every implementation should always have a freedom to differentiate when it comes down to the specific production level requirements where the security of a given application is more important than the compliance.

That's a really good point. I cannot argue with this. Reducing the the lest common denominator isn't a good idea when we're talking about security.

I suppose my concern is just that a compliant IDP might not work with a compliant server because servers have the freedom to make recommended claims required.

Just a thought. Does it make sense to allow MP JWT implementations to require recommended claims so long as they provide a way to disable the requirement? Implementations can still require recommended claims out-of-the-box for improved security but still work with all MP-JWT compliant IDPs if the developer is willing to disable those requirements? This is actually an approach that Payara has recently taken with the typ header claim giving us wider IDP support. A proprietary configuration can be set to disabled typ verification since not all IDPs provide the typ header and it's optional in RFC 7519.

**Comment by sberyozkin** [comment]
> I suppose my concern is just that a compliant IDP might not work with a compliant server because servers have the freedom to make recommended claims required.

What happens beyond the compliance requirements of MP JWT 1.2 is not our concern. A given implementation enforcing a given recommended claim as required has nothing to do with the MP JWT 1.2 compliance which is enforced by the TCK test suite.

> Does it make sense to allow MP JWT implementations to require recommended claims so long as they provide a way to disable the requirement? Implementations can still require recommended claims out-of-the-box for improved security but still work with all MP-JWT compliant IDPs if the developer is willing to disable those requirements?

How what are you suggesting is different to MP JWT 1.2 stance that the recommended claims can be made required my a given MP JWT server ? You are just turn it around and say: MP JWT makes all the claims required but is free to disable it.

IMHO MP JWT 1.2 tales approach - we start from the minimum required set and update this set going forward based on the evidence that some of these required claims are in wide use or on some best JWT security practices. We had to start from somewhere.

**Comment by sberyozkin** [comment]
One thing I would like to comment upon: there is no such thing as an `MP JWT compliant IDP` - it will never happen that all popular IDPs in use will start issuing their tokens by default such that these tokens can be accepted by MP JWT servers.  It is the other way around - it is in the interests of MP JWT to be able to accept as many tokens issued by IDPs as possible without setting a barrier beyond the absolute minimum.
For example, you can analyse the tokens issued by N most popular providers and check how many of those tokens have a properly set up `aud` claim OOB which is a recommended claim.
Ultimately MP JWT (Server) is about verifying the tokens and making them useful - it is not about trying to make the JWT tokens issued by IDPs and self-issued clients contain all the claims which may be considered a best practice from the point of view of MP JWT.

**Comment by ghunteranderson** [comment]
It sounds like we're saying that it is not the goal of this specification to provide token issuers with a set of requirements that, if met, would guarantee compatibility with all compliant MP JWT implementations. Instead, the specification is only intended to provide the minimum requirements for a server without restriction on additional requirements. Token issuers could not know that their tokens are compatible with all MP JWT compliant implementations unless they test all of those implementations.

If that's the case, then I'm probably arguing for a non-goal. I see value in placing restrictions on additional token requirements for the sake of compatibility but questioning the goals and non-goals of the specification is a much bigger topic than I want to approach.

**Comment by acoburn** [comment]
I will make a very concrete argument for why recommended claims should *not* be required. This is based on code that is currently running in production contexts.

I agree that if you are writing an identity provider (e.g. OIDC or based on OIDC) that generates JWT tokens, then yes, you will certainly want these _recommended_ claims to be present. Without those claims, you will likely be limiting yourself to the consumers of these tokens -- consumers that may not be using Java or MP-JWT at all but which will be expecting them in order to function.

However, and this is important, not all tokens generated by MP-JWT are generated by identity providers. There are categories of client applications that generate, for instance, [DPoP tokens](https://tools.ietf.org/html/draft-fett-oauth-dpop-04). (And I have written several that use MP-JWT, Smallrye-JWT in particular). DPoP tokens are JWT tokens, but they do not contain these recommended claims at all; in fact, those recommended claims are completely irrelevant in this context.

There are also contexts in which JWTs are passed between applications as a light-weight mechanism to prevent tampering. Again, the recommended claims of `sub`, `iss`, etc, might be irrelevant.

Ultimately, this depends on context. In certain contexts, these _recommended_ claims might really be required. But in other contexts, those assumptions do not hold.

**Comment by sberyozkin** [comment]
@ghunteranderson 

> It sounds like we're saying that it is not the goal of this specification to provide token issuers with a set of requirements that, if met, would guarantee compatibility with all compliant MP JWT implementations. 

No, it is not correct, please see below. What is correct here it is indeed a not-goal to attempt to certify IDPs for example, but the complete statement is not correct.

> Instead, the specification is only intended to provide the minimum requirements for a server without restriction on additional requirements. 

Identity Providers are issuing the tokens according to the best security practices, but also some claims can be present or absent depending on how a given Keycloak or other certified OIDC provider has had its realm or client properties configured - some may want to add, for example, `audience`, some - not. Most of these providers will set most of the recommended claims but it is indeed a non goal for this specification to start `certifying` those IDP providers.
Also see the comments from @acoburn.

> Token issuers could not know that their tokens are compatible with all MP JWT compliant implementations unless they test all of those implementations.

This is not correct/true - as long the token includes the required claims the issuer creates the tokens which will be accepted by all compliant MP JWT implementations.

As I said - we will aim at increasing the RECOMMENDED set - the specification text implies that but we need to move slowly as ultimately the goal is for MP JWT to accept as many tokens as possible without building the barriers like we did with the `groups` claim in `1.1.1` - where the users were complaining that their tokens have no `groups` and all the MP JWT implementations (most of them at least) have gone to support other claims anyway. Some providers like Keycloak can insert `groups` but some will never do it.

**Comment by sberyozkin** [comment]
@ghunteranderson 

Re my comment,
> it is indeed a non goal for this specification to start certifying those IDP providers.

That said, lets see how it goes. If we will get a really successful MP JWT specification in time, then we can consider having some kind of campaign where IDP providers can set `MP JWT Compliant` badge if they verify their tokens are verified by all the compliant  MP JWT implementations :-), but it is certainly not a goal now and IMHO even it it happens, the situation around `RECOMMENDED` vs `REQUIRED` would stay the same - the `REQUIRED` set may become larger but we may as well add more claims into a `RECOMMENDED` set, even if the margin will likely be smaller

**Comment by ghunteranderson** [comment]
Hey @sberyozkin. Thanks for bearing with me on this. 🙂 I want to be on the same page but I don't feel like I am 100% there yet.

> as long the token includes the required claims the issuer creates the tokens which will be accepted by all compliant MP JWT implementations.

I think there's a lot of value in this being true but I'm confused with how it doesn't contradict this excerpt from the spec.

> MP JWT implementations may enforce that JWT tokens contain all the recommended headers and claims.

For example, it sounds like you're saying a token with all required claims that does not include the recommended `typ` header must be accepted by all compliant MP JWT 1.2 implementations. However, the spec seems to give implementations permission to required `typ` and reject the token for not including it. Please correct me if I've misinterpreted your comment.

**Comment by ghunteranderson** [comment]
>If we will get a really successful MP JWT specification in time, then we can consider having some kind of campaign where IDP providers can set MP JWT Compliant badge if they verify their tokens are verified by all the compliant MP JWT implementations

I don't want to derail our thread with the idea of MP JWT compliant IDPs. The content of the token is what I really should have been focusing on in earlier comments. Still, I think this is a really great idea from a developer's perspective and I suspect IDPs would be interested if MP JWT was successful enough.

**Comment by sberyozkin** [comment]
@ghunteranderson 

> For example, it sounds like you're saying a token with all required claims that does not include the recommended typ header must be accepted by all compliant MP JWT 1.2 implementations. However, the spec seems to give implementations permission to required typ and reject the token for not including it. Please correct me if I've misinterpreted your comment.

There are many places in the spec, some of them originating from the very beginning, example, optional key sizes or algorithms. `RECOMMENDED` is in the same space - it is optional. Same as the MP JWT implementations may choose to require RSA keys 4096 bit or some obscure algorithm.  

`RECOMMENDED` is an advice for the issuers to include these claims but no more than that - and nowhere in the text it is suggested that the implementations which choose to check these claims have to reject the tokens without them - it is up to a concrete deployment instance. Some will decide to warn these claims are missing, some will default to something, etc. It would be really a non-interoperable friendly step to require for example to reject those tokens which have not set `typ` - it is implicit that JWT is expected, it is a good practice to include it - but is it a good reason to reject a token if some token has `typ` set to `BEARER` instead of `JWT`, IMHO - no...

thanks

**Comment by ghunteranderson** [comment]
@sberyozkin 
> and nowhere in the text it is suggested that the implementations which choose to check these claims have to reject the tokens without them

I see how the text doesn't suggest implementations reject them but it does seem to allow implementations to reject those tokens. I suppose I was expecting the spec to be more strict in this area than it is. However, I also get there's a tradeoff with security when the upper bound on requirements becomes more strict; something I hadn't considered before opening this issue.

I'm happy with closing the issue at this point but I'll hold off a bit in case you or @acoburn have any last remarks.

Thanks again for your time on this issue. 🙂

**Comment by sberyozkin** [comment]
@ghunteranderson Well, we can just drop the whole section about the RECOMMENDED claims (i.e, do not advice anything at all) but would the spec win :-) ? Like I said, since these claims are effectively optional, it is in the optional space how the implementations may react to their presence or absence. Asking the implementations to reject the claims would make these claims required - which would also be too strong given that some implementations may not need a given claim. 
True, because it is optional, the implementations are allowed to do whatever they want around these claims. The spec does not require any particular course of action. But the same is true for the optional key sizes and algorithms - we can say that yes, some implementations may actually require in a particular deployment 4K RSA keys. Same situation IMHO.

Thanks

**Comment by sberyozkin** [comment]
@ghunteranderson thanks; I think it would make sense to make some text clarifications in 2.0, lets continue the discussion later

**Comment by ghunteranderson** [comment]
@sberyozkin Sounds good. Thanks again for going back and forth with me on this. The MicroProfile specs are important for my work and I'd love to help however I can. 🙂
