### ISSUE TITLE
Both scopes or one scope?

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-jwt-auth#27]
We had a similar issue on the JMS spec, and it leads to a potentially much more complex implementation

https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/interoperability.asciidoc#cdi-injection-requirements

In this section, its declared that we need to support injection of either RequestScoped or Dependent scoped identity.  Is dependent really appropriate here?  What is the use case?

I would prefer to see request scoped only, unless there's some specific need.

**Comment by starksm64** [comment]
A producer for a javax.injection.Provider<String> requires Dependent scope due to the unproxyable nature of String. I raised an issue with the CDI spec on why the javax.injection.Provider is not essentially a wrapper, thus creating a proxyable type and did not get a satisfactory answer.

**Comment by starksm64** [comment]
So based on today's MP-JWT call, what this issue comes down to is the following:
1. The JsonWebToken needs @RequestScoped scoping.
2. The associated claim values need @Dependent scoping and implementations should verify that injection of a raw claim value into a non-requestscoped context results in an error or warning.

**Comment by johnament** [comment]
Sorry I had to head out early.  What I would recommend:

- Optional, String, Long, Date etc injection points have scope dependent
- All other injection points have request scope

It would be preferable that we don't even call out injection of provider & instance, since those are built in CDI constructs.

**Comment by starksm64** [comment]
Should we just say any non-proxyable type as defined by the CDI spec must have dependent scope, and list a few example like you have mentioned?

**Comment by johnament** [comment]
I guess its a question of what we consider to be the finite list of fields injectable with `@Claim`.  I think the spec should clarify that.

What I'm now seeing is that in order to create any `@Claim` injection point, I need the JWT and the requested claim, which means I always need dependent scope beans.

**Comment by Emily-Jiang** [comment]
I agree this JsonWebToken bean should not have two scopes. However, I think it should match to the in-built Principal bean provided by CDI, because JsonWebToken is an extension to Principal. In CDI spec, there is a builtin Principal bean provided and it is Dependent scope. I ran this past Weld-dev team. Martin Kouba confirmed _"It's @Dependent. But a special proxy is injected and SPI 
org.jboss.weld.security.spi.SecurityServices.getPrincipal() is invoked 
to obtain the current caller identity for every invocation of an 
injected reference. Well, it works similar to how @Dependent stateless session beans work. 
Unlike @RequestScoped there is no real CDI context just a special proxy 
that delegates to SPI."_

Arjan Tijms later commented "Indeed, it can't be really request scope, since the principal can potentially change many times during a request. Though, once initially set it normally applies for the remainder of the web request. For other usages of the request scope it's not so well defined in EE actually.".

Do you guys think this JsonWebToken should behave the same as the in-built Principal bean? If not, please explain why?

**Comment by starksm64** [comment]
I don't believe it should behave the same as the CDI javax.security.Principal bean due to the fact that the JsonWebToken based principal is bound to the current javax.servlet.http.HttpServletRequest via the Authentication header of the current request. Changing the Principal along the flow of a request is possible, but it does not apply to the JsonWebToken based principal. It is a change in the current caller by either impersonation, or by pushing a newly authenticated Principal onto the stack. 

The other issue with making it @Dependent is that strictly speaking this would break injection of the JsonWebToken into an @ApplicationScoped endpoint. Per the CDI spec this would mean the JsonWebToken could be created once on the creation of the endpoint, and end up out of sync with the subsequent requests.

It sounds like weld is treating the Principal more like a javax.inject.Provider<Principal> rather than a true @Dependent scope bean.

**Comment by starksm64** [comment]
With the comment about JsonValue subtypes being non-proxyable, there essentially are only dependent scoped claim values.

**Comment by johnament** [comment]
In most impls (and I can confirm within the Keycloak adapter), the KeycloakPrincipal is not injectable but it is bound to the actual request.  Also note that you get the principal from the request, so I don't think it would be a bad idea to fall back to the CDI behavior, especially since everything else is turning into a dependent scoped bean.

**Comment by starksm64** [comment]
And what about the issue we discussed with injection dependent values into application/session scoped beans? Is the same caching problem going to exist there for a usage like this now:

```java
@ApplicationScoped
public class AppScopedEndpoint {
    @Inject
    JsonWebToken jwt;
```

If so, we are now down to only dependent scope objects with a requirement to validate any injection of non-Provider wrapped value into application/session scope as an error.

**Comment by johnament** [comment]
That should be an `Instance<JsonWebToken>`.  One of the things missed in the call is that generally speaking, injecting a dependent bean using an `Instance` (Instance extends Provider) is generally considered bad practice.  To safely do it, you need to:

```java
@Inject
Instance<JsonWebToken> jwtInstance;
public void doWork() {
    JsonWebToken token = jwtInstance.get();
    // do real work
    jwtInstance.destroy(token); // clean up the floating instance
}
```

**Comment by starksm64** [comment]
We have the JsonWebToken at RequestScoped and all claim values at Dependent scoped for 1.0.
