### ISSUE TITLE
MicroProfile Interoperable JWT RBAC 1.2 Compatible Certification Request - Payara Community 5.2021.10

### ISSUE THREAD

**Issue by bacehanural** [eclipse/microprofile-jwt-auth#283]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
[Payara Services Ltd.](https://www.payara.fish/)

- [x] Product Name, Version and download URL (if applicable):<br/>
[Payara Platform Community 5.2021.10 Release](https://www.payara.fish/downloads/payara-platform-community-edition/)

- [x] Specification Name, Version and download URL:<br/>
[MicroProfile Interoperable JWT RBAC 1.2](https://download.eclipse.org/microprofile/microprofile-jwt-auth-1.2/microprofile-jwt-auth-spec-1.2.html)

- [x] Public URL of TCK Results Summary:<br/>
[MicroProfile TCK Results](docs/modules/ROOT/pages/microprofile-tck-certification/5.2021.10/microprofile-tck-results-full-5.2021.10.adoc)

- [x] Any Additional Specification Certification Requirements:<br/>
No

- [x] Java runtime used to run the implementation:<br/>

zulu 8

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>

AWS, Ubuntu 20.04

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by Emily-Jiang** [comment]
> Thanks for opening this request, my understanding these requests have to be created once to support a given release, for example, for `1.2` it was #227, for `2.0` - #269.

What you mentioned is the minimum requirement for releasing a spec. This issue is to certify a runtime after the release.
It is okay for a runtime to submit a CCR here to certify the support of a particular release of the corresponding spec. However, it will save time to just raise a CCR to cover all of MP 4.1 specs on the eclipse/microprofile repo. At the moment, we are standardising the TCK certification process [here](https://github.com/microprofile/microprofile-wg/pull/118). Once MP WG agrees, we will publicise the process so that everyone can follow. Hopefully, we will settle this soon. You can leave this issue for now.

**Comment by sberyozkin** [comment]
I believe we can close this issue now, IMHO the list of open issues should be about fixing something in the MP JWT spec
