### ISSUE TITLE
TCK: RolesAllowedTest only tests sub-resource methods

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-jwt-auth#77]
I.e. only methods annotated with `@Path`. However, in JAX-RS _"Resource methods are methods of a resource class annotated with a request method designator"_ (e.g. `@GET`). So `@RolesAllowed` should probably also work for the following resource method:

```java
@Path("/foo")
@DenyAll
class Endpoint {

  @RolesAllowed("Foo")
  @GET
  String getList();
     // TODO
  }
```

**Comment by sberyozkin** [comment]
Hi Martin @mkouba, if you don't mind we can close this issue because it is more or less orthogonal as to where the resource handler is within the JAX-RS application, otherwise we'd need to have all the TCK tests updated to test both the regular and sub resources :-) but we'd not expand the MP JWT coverage but rather will test how a given container/JAX-RS is able to check subresources vs regular resources :-)

**Comment by mkouba** [comment]
Well, I think it wouldn't hurt to test such a basic use case. But feel free to close this issue ;-).

**Comment by sberyozkin** [comment]
Hi Martin, @mkouba, I actually do not see a single subresource locator method in this [endpoint class](https://github.com/eclipse/microprofile-jwt-auth/blob/master/tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RolesEndpoint.java). I'm just  trying to minimize the list of issues keeping only those which are really relevant and for which I will try to find the time for, as the list of issues has become stale.  
So let me indeed close this issue for now, thanks
